export const notes = [
  { name: "C3", midi: 48, octave: true },
  { name: "C#3", midi: 49, sharp: true },
  { name: "D3", midi: 50 },
  { name: "D#3", midi: 51, sharp: true },
  { name: "E3", midi: 52 },
  { name: "F3", midi: 53 },
  { name: "F#3", midi: 54, sharp: true },
  { name: "G3", midi: 55 },
  { name: "G#3", midi: 56, sharp: true },
  { name: "A3", midi: 57 },
  { name: "A#3", midi: 58, sharp: true },
  { name: "B3", midi: 59 },
  { name: "C4", midi: 60, octave: true },
  { name: "C#4", midi: 61, sharp: true },
  { name: "D4", midi: 62 },
  { name: "D#4", midi: 63, sharp: true },
  { name: "E4", midi: 64 },
  { name: "F4", midi: 65 },
  { name: "F#4", midi: 66, sharp: true },
  { name: "G4", midi: 67 },
  { name: "G#4", midi: 68, sharp: true },
  { name: "A4", midi: 69 },
  { name: "A#4", midi: 70, sharp: true },
  { name: "B4", midi: 71 },
  { name: "C5", midi: 72, octave: true },
];

export const sortedNotes = notes.sort((a, b) => b.midi - a.midi);
