export const notes = [
  { name: "C3", pitch: 48, octave: true },
  { name: "C#3", pitch: 49, sharp: true },
  { name: "D3", pitch: 50 },
  { name: "D#3", pitch: 51, sharp: true },
  { name: "E3", pitch: 52 },
  { name: "F3", pitch: 53 },
  { name: "F#3", pitch: 54, sharp: true },
  { name: "G3", pitch: 55 },
  { name: "G#3", pitch: 56, sharp: true },
  { name: "A3", pitch: 57 },
  { name: "A#3", pitch: 58, sharp: true },
  { name: "B3", pitch: 59 },
  { name: "C4", pitch: 60, octave: true },
  { name: "C#4", pitch: 61, sharp: true },
  { name: "D4", pitch: 62 },
  { name: "D#4", pitch: 63, sharp: true },
  { name: "E4", pitch: 64 },
  { name: "F4", pitch: 65 },
  { name: "F#4", pitch: 66, sharp: true },
  { name: "G4", pitch: 67 },
  { name: "G#4", pitch: 68, sharp: true },
  { name: "A4", pitch: 69 },
  { name: "A#4", pitch: 70, sharp: true },
  { name: "B4", pitch: 71 },
  { name: "C5", pitch: 72, octave: true },
];

export const sortedNotes = notes.sort((a, b) => b.pitch - a.pitch);
